services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "52520:5432"
    environment:
      POSTGRES_USER: alice
      POSTGRES_PASSWORD: alice
      POSTGRES_DB: smartbar
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

# TODO: Schema & Table init issues.
