openapi: 3.1.2
info:
  title: Smartbar Backoffice API
  description: Smartbar Backoffice API
  version: 1.0.0
paths:
  /categories:
    get:
      operationId: getCategories
      tags:
        - Categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/apiCategory"
    post:
      operationId: postCategory
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiCategory"
      responses:
        201:
          description: Success
          $ref: "#/components/responses/201"
  /categories/{categoryId}:
    parameters:
      - name: categoryId
        schema:
          $ref: "#/components/schemas/id"
        in: path
        required: true
        style: simple
    put:
      operationId: putCategory
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiCategory"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteCategory
      tags:
        - Categories
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getCategory
      tags:
        - Categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiCategory"
  /articles:
    get:
      operationId: getArticles
      tags:
        - Articles
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/apiArticle"
    post:
      operationId: postArticle
      tags:
        - Articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiArticle"
      parameters:
        - name: x-category-id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      responses:
        201:
          $ref: "#/components/responses/201"
  /articles/{articleId}:
    parameters:
      - name: articleId
        schema:
          $ref: "#/components/schemas/id"
        in: path
        required: true
    put:
      operationId: putArticle
      tags:
        - Articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiArticle"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteArticle
      tags:
        - Articles
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getArticle
      tags:
        - Articles
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiArticle"
  /tables:
    get:
      operationId: getTables
      tags:
        - Tables
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/apiTable"
    post:
      operationId: postTable
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiTable"
      responses:
        201:
          $ref: "#/components/responses/201"
  /tables/{tableId}:
    parameters:
      - name: tableId
        schema:
          $ref: "#/components/schemas/id"
        in: path
        required: true
    put:
      operationId: putTable
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiTable"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteTable
      tags:
        - Tables
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getTable
      tags:
        - Tables
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiTable"
components:
  schemas:
    id:
      type: integer
      format: int64
    apiCategory:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        name:
          type: string
        description:
          type: string
    apiArticle:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        name:
          type: string
        price:
          type: number
        description:
          type: string
        picture:
          type: string
    apiTable:
      type: object
      required:
        - name
        - seatCount
        - active
      properties:
        id:
          $ref: "#/components/schemas/id"
        name:
          type: string
        seatCount:
          type: integer
        active:
          type: boolean
  responses:
    201:
      description: Entity successfully created
      headers:
        Location:
          description: Entity successfully created
          schema:
            type: string
