quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      db-name: smartbar
    jdbc:
      additional-jdbc-properties:
        - currentSchema: smartbar
  hibernate-orm:
    database:
      default-schema: smartbar
    log:
      sql: true
    schema-management:
      create-schemas: true
