quarkus:
  datasource:
    db-kind: postgresql
    jdbc: false
    reactive:
      additional-properties:
        - currentSchema: smartbar
  hibernate-orm:
    database:
      default-schema: smartbar
    log:
      sql: true
    schema-management:
      create-schemas: true
  oidc:
    client-id: smartbar-backoffice
    application-type: web-app
