quarkus:
  datasource:
    reactive:
      url: vertx-reactive:postgresql://should-come-from-env
    password: should-come-from-env
    username: should-come-from-env
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
