quarkus:
  test:
    continuous-testing: PAUSED
  datasource:
    devservices:
      port: 52520
      reuse: true
      show-logs: true
  http:
    auth:
      form:
        enabled: true
        login-page: ""
        landing-page: ""
