quarkus:
  datasource:
    reactive:
      url: vertx-reactive:postgresql://should-come-from-env
    password: should-come-from-env
    username: should-come-from-env
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  http:
    insecure-requests: DISABLED
    ssl:
      certificate:
        key-store-file: /not/defined
        key-store-file-type: PKCS12
        trust-store-file: /not/defined
        trust-store-file-type: PKCS12
        reload-period: 1h
    enable-compression: true
    compressors:
      - deflate
      - gzip
      - br
