quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      db-name: smartbar
    jdbc: false
    reactive:
      additional-properties:
        - currentSchema: smartbar
  hibernate-orm:
    database:
      default-schema: smartbar
    log:
      sql: true
    schema-management:
      create-schemas: true
  http:
    insecure-requests: redirect
    ssl:
      certificate:
        key-store-file: keystore.p12
        key-store-file-type: PKCS12
